# Generated by Django 4.0.10 on 2024-02-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_group', '0004_remove_socialgroupmember_is_invited'),
        ('account', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sg_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='social_group.socialgroup'),
            preserve_default=False,
        ),
    ]
