# Generated by Django 4.0.10 on 2024-02-03 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_group', '0004_remove_socialgroupmember_is_invited'),
        ('account', '0004_notification_sg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='is_invitation',
        ),
        migrations.AlterField(
            model_name='notification',
            name='sg_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_group.socialgroup'),
        ),
    ]
