# Generated by Django 4.0.10 on 2024-02-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_group', '0002_socialgroup_privacy_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialgroupmember',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
    ]
