# Generated by Django 4.0.10 on 2024-02-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_group', '0003_socialgroupmember_is_invited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialgroupmember',
            name='is_invited',
        ),
    ]
