# Generated by Django 4.0.10 on 2024-02-03 15:29

from django.db import migrations, models


def populate_social_group_member_roles(apps, schema_editor):
    SocialGroupMember = apps.get_model('social_group', 'SocialGroupMember')
    for member in SocialGroupMember.objects.all():
        # if the member has "member" role, change it to moderator
        if member.role == 'member':
            member.role = 'moderator'
            member.save()


class Migration(migrations.Migration):
    dependencies = [
        ('social_group', '0005_socialgroupevent_socialgroupeventmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialgroupmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('guest', 'Guest')],
                                   max_length=50),
        ),
        migrations.RunPython(populate_social_group_member_roles),
    ]
