# Generated by Django 4.0.10 on 2024-02-03 15:32

from django.db import migrations, models


def populate_social_group_member_roles(apps, schema_editor):
    SocialGroupMember = apps.get_model('social_group', 'SocialGroupMember')
    for member in SocialGroupMember.objects.all():
        # if the member has "member" role, change it to moderator
        if member.role == 'guest':
            member.role = 'member'
            member.save()


class Migration(migrations.Migration):
    dependencies = [
        ('social_group', '0006_alter_socialgroupmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialgroupmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')],
                                   max_length=50),
        ),
        migrations.RunPython(populate_social_group_member_roles),

    ]
