# Generated by Django 4.0.10 on 2024-02-02 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_group', '0002_socialgroup_privacy_comment'),
        ('event', '0002_remove_event_date_event_begin_ts_event_end_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sg_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social_group.socialgroup'),
            preserve_default=False,
        ),
    ]
