"""
Django settings for flatscan project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import logging
from pathlib import Path
from urllib.parse import quote_plus

from django.utils.translation import gettext_lazy as _

logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV = os.getenv("ENV")
SECRET_KEY = os.getenv("SECRET_KEY")

if ENV == 'prod':
    DEBUG = False
else:
    DEBUG = True
ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'corsheaders',  # Remove this line
    # 'rest_framework',  # Remove this line
    'account',
    'location',
    'social_group',
    'event'
]

MIDDLEWARE = [
    # 'corsheaders.middleware.CorsMiddleware',  # Remove this line
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# REACT APP URL
CORS_ORIGIN_WHITELIST = [
    'http://localhost:4000',
]

ROOT_URLCONF = 'ipr_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.contrib.auth.context_processors.auth',
                'social_group.context_processors.add_current_group_id',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',
    ],
    'NON_FIELD_ERRORS_KEY': 'detail',

}

WSGI_APPLICATION = 'ipr_app.wsgi.application'
#
# MONGO_DB_USERNAME = os.getenv('MONGO_DB_USERNAME')
# MONGO_DB_PASSWORD = os.getenv('MONGO_DB_PASSWORD')
# MONGO_DB_ATLAS_CLUSTER = os.getenv('MONGO_DB_ATLAS_CLUSTER')
# MONGO_DB_NAME = os.getenv('MONGO_DB_NAME')
#
# # Escape the username and password using quote_plus
# escaped_username = quote_plus(MONGO_DB_USERNAME)
# escaped_password = quote_plus(MONGO_DB_PASSWORD)
# MONGO_DB_HOST = f'mongodb+srv://{escaped_username}:{escaped_password}@{MONGO_DB_ATLAS_CLUSTER}/{MONGO_DB_NAME}?retryWrites=true&w=majority'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("SQL_DB_NAME"),
        'USER': os.getenv("SQL_DB_USER"),
        'PASSWORD': os.getenv("SQL_DB_PASSWORD"),
        'HOST': os.getenv("SQL_DB_HOST"),
        'PORT': os.getenv("SQL_DB_PORT"),
        'OPTIONS': {
            'charset': 'utf8mb4'  # This is the important line
        }
    },
}

STATIC_URL = '/staticfiles/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "staticfiles/"),
)
#
# MONGODB_DATABASES = {
#     "default": {
#         "name": MONGO_DB_NAME,
#         "host": MONGO_DB_HOST,
#         "password": MONGO_DB_PASSWORD,
#         "username": MONGO_DB_USERNAME,
#         "tz_aware": True,  # if you using timezones in django (USE_TZ = True)
#     },
# }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'account.User'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

DEFAULT_LANGUAGE = 1

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = (
    ('pl', _('Polish')),
    ('en', _('English')),
)

ENABLE_LANGUAGE_CHANGE = False

LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = 587
EMAIL_USE_TLS = False

CONTACT_EMAIL_RECEIVER = os.getenv("DEFAULT_CONTACT_EMAIL")
DEFAULT_CONTACT_EMAIL = os.getenv("DEFAULT_CONTACT_EMAIL")
DEFAULT_NOTIFICATION_EMAIL = os.getenv("DEFAULT_NOTIFICATION_EMAIL")

# SIGN IN

LOGIN_URL = _("/login/")
# Sign In
LOGIN_REDIRECT_URL = '/'  # Redirect after login (default is profile)
LOGOUT_REDIRECT_URL = '/login/'  # Redirect after logout
# TRAITS


INTERNAL_IPS = [
    "localhost",
    "127.0.0.1",
]
# LOGGING SETTINGS

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO'
    },
}

PASSWORD_VALIDATION_REGEX = '((?=.*\d)' \
                            '(?=.*[A-Za-z])' \
                            '(?=.*[/\|<>`!@#$%^&*()_.?+=[\]{};:\'÷"”£€¢~§-])' \
                            '.{8,100})'
